# Generated by Django 5.0.3 on 2024-03-25 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='DrivingAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателей',
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характер отказа',
                'verbose_name_plural': 'Характеры отказа',
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модели техники',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид технического обслуживания',
                'verbose_name_plural': 'Виды технических обслуживаний',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.CharField(max_length=50, unique=True)),
                ('engine_id', models.CharField(max_length=50)),
                ('transmission_id', models.CharField(max_length=50)),
                ('driving_axle_id', models.CharField(max_length=50)),
                ('controlled_axle_id', models.CharField(max_length=50)),
                ('delivery_contract', models.TextField()),
                ('factory_shipment_date', models.DateField(default=django.utils.timezone.now)),
                ('end_consumer', models.TextField()),
                ('delivery_address', models.TextField()),
                ('specification', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('controlled_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.controlledaxle', verbose_name='Модель управляемого моста')),
                ('driving_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.drivingaxle', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.engine', verbose_name='Модель двигателя')),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.machinemodel', verbose_name='Модель техники')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.transmission', verbose_name='Модель трансмиссии')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now)),
                ('operating_time', models.PositiveIntegerField()),
                ('work_order_number', models.CharField(max_length=100)),
                ('work_order_date', models.DateField(default=django.utils.timezone.now)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='silant_app.machine')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.maintenancetype')),
                ('maintenance_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_failure_date', models.DateField(default=django.utils.timezone.now)),
                ('operating_time', models.PositiveIntegerField()),
                ('equipment_failure_description', models.TextField()),
                ('used_spare_parts', models.TextField()),
                ('recovery_date', models.DateField(default=django.utils.timezone.now)),
                ('downtime_of_equipment', models.IntegerField()),
                ('failure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.failure')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='silant_app.machine')),
                ('equipment_recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany')),
            ],
        ),
    ]
