# Generated by Django 5.0.3 on 2024-04-03 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='controlledaxle',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемого моста'},
        ),
        migrations.AlterModelOptions(
            name='drivingaxle',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Техническое обслуживание', 'verbose_name_plural': 'Технические обслуживания'},
        ),
        migrations.AlterField(
            model_name='claims',
            name='downtime_of_equipment',
            field=models.IntegerField(verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='equipment_failure_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='equipment_failure_description',
            field=models.TextField(verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='equipment_recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='failure_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.failure', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='silant_app.machine', verbose_name='Mашина'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='operating_time',
            field=models.PositiveIntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='recovery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany', verbose_name='Cервисная компания'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='used_spare_parts',
            field=models.TextField(blank=True, verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='controlled_axle_id',
            field=models.CharField(max_length=50, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_contract',
            field=models.CharField(max_length=255, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='driving_axle_id',
            field=models.CharField(max_length=50, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='end_consumer',
            field=models.CharField(max_length=100, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_id',
            field=models.CharField(max_length=50, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factory_shipment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='specification',
            field=models.TextField(verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_id',
            field=models.CharField(max_length=50, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='silant_app.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.maintenancetype', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.PositiveIntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_number',
            field=models.CharField(max_length=100, verbose_name='№ заказ-наряда'),
        ),
    ]
