# Generated by Django 5.0.3 on 2024-04-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0003_alter_claims_options_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claims',
            table='claims',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='machines',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='maintenance',
        ),
    ]
